### ISSUE TITLE
Not working with Vivaldi

### ISSUE THREAD

**Issue by tom3456** [JanisEst/KeePassBrowserImporter#13]
Hello,

the import from Vivaldi is not working. I tried by selecting "chromium" in the dialog but the chromium folder does not exists. The folder location for Vivaldi is "C:\Users\xxx\AppData\Local\Vivaldi".

**Comment by JanisEst** [comment]
Vivaldi works fine for me. Just choose the profile path `C:\Users\xxx\AppData\Local\Vivaldi\User Data\Default`.
