### ISSUE TITLE
Plugin not loading ?

### ISSUE THREAD

**Issue by gamersalpha** [JanisEst/KeePassBrowserImporter#15]
hello so i put the plugin in the directory : 

![image](https://user-images.githubusercontent.com/32466950/36946129-5e379252-1fb8-11e8-834a-99fb9e8a0ed9.png)
and when i go to plugin menu : 

![image](https://user-images.githubusercontent.com/32466950/36946135-6e8309e8-1fb8-11e8-91e5-3de5cc31cf0e.png)

i have nothing : 

![image](https://user-images.githubusercontent.com/32466950/36946137-79aa70a4-1fb8-11e8-9d5a-8e4af8dfd08c.png)

what i doing wrong ?

thanks

**Comment by JanisEst** [comment]
Did you restart KeePass? If KeePass can't load a plugin you will see a message box.

**Comment by gamersalpha** [comment]
yes  i m using keeepass 1

now with keepas 2
works
