### ISSUE TITLE
NSS_Init failed : Wrong profile path - Keepass 2.38 - Firefox 58.0.2 

### ISSUE THREAD

**Issue by gamersalpha** [JanisEst/KeePassBrowserImporter#16]
Hello, 
so import browser not working 

![image](https://user-images.githubusercontent.com/32466950/36990598-7d7ac920-20a5-11e8-9a96-975cc8a3dc98.png)

what do u think please ?

**Comment by Pro** [comment]
Same problem here...
@JanisEst any suggestions on this?

I already tried with FF x86 and x64, resetting the profile, using older KeePass, but no luck.

**Comment by JanisEst** [comment]
Could you please try https://github.com/JanisEst/KeePassBrowserImporter/releases/tag/v1.0.5 ? I have tested this version with the latest Firefox and everything works.

**Comment by Pro** [comment]
It worked now, thank you very much for the update!!!
