### ISSUE TITLE
"The specified module could not be found" when trying to import from Firefox 60.0.1

### ISSUE THREAD

**Issue by gwestwood** [JanisEst/KeePassBrowserImporter#18]
I've installed the plugin in KeePass, but when I try to import from any profile from Firefox Quantum version 60.0.1 (64-bit) I get the message "The specified module could not be found":

![keepassbrowserimporter](https://user-images.githubusercontent.com/31341494/40885834-da41d3a8-6725-11e8-8d7c-b988e660d646.png)

I have checked and I do have .Net4 installed and up-to-date,  so I am uncertain as to where the issue lies.  Please can you assist?

**Comment by verbage** [comment]
Same issue here, but I am using v60.0.2 of Firefox (all other stuff the same).

**Comment by JanisEst** [comment]
Could you please try https://github.com/JanisEst/KeePassBrowserImporter/releases/tag/v1.0.5 ? I have tested this version with the latest Firefox and everything works.
