### ISSUE TITLE
Importing the passwords takes a long time

### ISSUE THREAD

**Issue by Tusinski** [JanisEst/KeePassBrowserImporter#19]
Importing the passwords takes a long time. I quit after an hour. Is that normal?

**Comment by JanisEst** [comment]
No, it takes only seconds. By default the plugin tries to connect to the website of the entry to extract the title and the icon. This could be a problem if you need a proxy / lots of sites aren't available. Then every request will run into a timeout which may increase the import time. But that should not sum up to an hour. You should close the browser you try to import from, maybe it blocks a needed file or something.
