### ISSUE TITLE
Error when loading passwords from FireFox 61.0.1

### ISSUE THREAD

**Issue by AgPeHaJIuH1** [JanisEst/KeePassBrowserImporter#20]
![image](https://user-images.githubusercontent.com/29563929/43460962-db93ad7a-94da-11e8-9f85-e1f5f09a332c.png)

**Comment by JanisEst** [comment]
You get this error with KeePassBrowserImporter 1.0.5?

**Comment by AgPeHaJIuH1** [comment]
Yes

**Comment by JanisEst** [comment]
Works now again with 1.0.7

https://github.com/JanisEst/KeePassBrowserImporter/releases/tag/v1.0.7
