### ISSUE TITLE
No working in IE/EDGE

### ISSUE THREAD

**Issue by indevor** [JanisEst/KeePassBrowserImporter#21]
Hi. The password backup does not work in ( IE/EDGE ) OS version 10.0.15063.1266 (Win10 RS2).
I get 3 identical accounts, Instead of three different.
![1](https://user-images.githubusercontent.com/6624673/44806742-71776f00-abd0-11e8-8aff-157fb555a88b.jpg)
![2](https://user-images.githubusercontent.com/6624673/44806743-71776f00-abd0-11e8-9990-3372e2428276.jpg)

**Comment by indevor** [comment]
KeePassBrowserImporter 1.0.5

**Comment by indevor** [comment]
I compiled your class (InternetExplorer.cs) separately into the application:
in: private IEnumerable<EntryInfo> ReadVaultPasswords()


`for (var i = 0; i <vaultCount; ++ i)`

"i" never happens more> 0

**Comment by JanisEst** [comment]
There was a second error because the `propertyPtr` was not set to `IntPtr.Zero` for the second item. If this parameter is not null, the `VaultGetItem` method fails.
