### ISSUE TITLE
Firefox 63.0.1 (64bit) error loading credentials

### ISSUE THREAD

**Issue by sqdesign** [JanisEst/KeePassBrowserImporter#23]
![kp_error](https://user-images.githubusercontent.com/33090628/48311205-82fbd080-e59c-11e8-84e5-6bef3fe9d31b.jpg)

**Comment by handfreezer** [comment]
same for me
I have a master password set, but the problem persist if I remove it.

**Comment by Strandbar4711** [comment]
Problem confirmed, no import possible. Same error message.

**Comment by Reiner666Hans** [comment]
Same issue here. Import with Firefox

**Comment by zjw** [comment]
This issue is likely a duplicate of issue #22.  A work-around for the issue can be found there.

**Comment by JanisEst** [comment]
Works now again with 1.0.7

https://github.com/JanisEst/KeePassBrowserImporter/releases/tag/v1.0.7
