### ISSUE TITLE
Problem installing KeePassBrowserImporter V1.0.* into Keepass 2.38 in Ubuntu 18.04

### ISSUE THREAD

**Issue by mike4git** [JanisEst/KeePassBrowserImporter#25]
I've a problem installing KeePassBrowserImporter in my Keepass (Version 2.38).
Independently which version of KeePassBrowserImporter I took, I ran into the same problem after copying this plugin file into my folder:
/usr/lib/keepass2 in Ubuntu 18.04.
After restart of Keepass it told me that:
![keepasserror](https://user-images.githubusercontent.com/5848798/51922394-40060800-23e9-11e9-9608-22bdc515f203.png)
What can I do?

**Comment by JanisEst** [comment]
I don't know what the problem is but this plugin doesn't work on *nix systems. The decryption routines are windows specific. I currently don't have plans to support other platforms. If someone is willing to make a PR with the needed changes I will be happy to merge it.

**Comment by JanisEst** [comment]
I have modified the readme so the circumstance is more visible. (b1050d0)
