### ISSUE TITLE
message of the day causes username to not populate

### ISSUE THREAD

**Issue by ZenMasta** [JanisEst/KeePassBrowserImporter#41]
https://secure2.procharge.com/Merchantlogin.aspx

This website sometimes has a warning/alert and when that happens, the username field won't populate.

**Comment by JanisEst** [comment]
Your problem sounds like you want to populate the form with credentials from KeePass. In this case the problem is not related to this plugin.

**Comment by ZenMasta** [comment]
No, it's for sure a plugin issue. 
If you check the website today you can see a big red message of the day at the top. whenever they have these messages, the browser plugin will not populate the username field.

**Comment by JanisEst** [comment]
No, it's not. The plugin reads data from the browser profile files. It does not interact in any way with a running browser instance and therefore can't populate any form fields.
