### ISSUE TITLE
Cant download Release Files

### ISSUE THREAD

**Issue by MaplePhoenex** [JanisEst/KeePassBrowserImporter#42]
Cant download Release Files just errors. Nothing on my end. Only reason i was going to use KeePass. Now it Defeats the point.

**Comment by cristianst85** [comment]
Can you be more explicit? What release files are you referring to?

**Comment by JanisEst** [comment]
https://github.com/JanisEst/KeePassBrowserImporter/releases/tag/v1.0.9

Download works fine.
