### ISSUE TITLE
DestroyIcon error message.

### ISSUE THREAD

**Issue by joravasal** [JanisEst/KeePassBrowserImporter#8]
Hi,

Just started using KeePass and tried to import my passwords from Firefox with your plugin. But something goes wrong as soon as I try to open the importer. I'm using KeePass 2.25 on LinuxMint.

![snap14](https://cloud.githubusercontent.com/assets/3131788/18284749/dce638ac-7473-11e6-8f4f-edf2358358af.jpg)

Let me know how can I help to debug this. Thanks!

**Comment by KN4CK3R** [comment]
I don't know if the plugin will work with linux. The firefox import uses some DLL files from mozilla to decrypt the database. I don't think this works with linux and mono.
As far as I know Google Chrome stores credentials in the keyring so this import doesn't work with linux too.
Your best chances are to fire up a virtual machine with windows and copy your firefox profile and KeePass there. Open your database, import the profile and copy KeePass back to linux.

---
I don't know why you get this error message. Must be an error message from inside Mono.

**Comment by TheGrave** [comment]
Confirming it's broken on Linux - same error. KeePass version 2.41, OS: Lubuntu 18.04 x64, plugin version 1.0.8.0.

**Comment by JanisEst** [comment]
The whole plugin doesn't support linux so I don't think this is a problem to care about.
